baseurl = "http://levex.github.io/"
languageCode = "en-us"
title = "Programmers' Tea Lounge"

[params]
AuthorName = "Levente Kurusa"
AuthorEmail = "levex@linux.com"
Tagline = "Concurrency, Haskell, C, low-level programming and my adventures into academia"
HomepagePosts = 3
SocialLinks = true
GithubUsername = "levex"
TwitterUsername = "ilevex"
